### ISSUE TITLE
[FEAT] 상점 뷰 구현

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#12]
## 🛠 Issue

상점 뷰를 구현합니다.
이미지만 들어간 버튼 컴포넌트 작업을 추가로 진행합니다.
Alert 액션 등, 구매 이후 일어나는 액션도 구현합니다.

## 📝 To-do

- [x] 상점 뷰에 필요한 컴포넌트 배치
- [x] 컴포넌트 탭 할 경우 일어나는 액션 구현
- [x] Alert 화면 구현
