### ISSUE TITLE
[FEAT] 맵 뷰 기본 사항 구현

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#4]
## 🛠 Issue

맵 뷰의 기본 사항을 구현합니다.
현재 위치 표시, 위치 트래킹, 포인트 마커 구현을 실행합니다.

## 📝 To-do

- [ ] 현재 위치 표시 버튼 추가
- [ ] 현재 위치 표시 마커 버튼 클릭시 나타나게 하기
- [ ] 첫 진입 시 맵 Level 조정(반경 2km 정도 보이는 축척으로)
- [ ] 이동 시 현재 위치 마커 이동 구현
- [ ] 이동 시 지나온 거리 표시
- [ ] 포인트 마커 5개 구현
