### ISSUE TITLE
[FEAT] Map을 제외한 뷰 연결, CoreData 기능 뷰와 연결

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#46]
## 🛠 Issue

Map을 제외한 뷰 연결, CoreData 기능 뷰와 연결

## 📝 To-do

- [x] CoreData 메서드 뷰와 연결
- [x] 캐릭터 옷입히기 구현
- [x] 상점 뷰 캐릭터 옷 갈아입기, 구입하기 구현
- [x] 메인뷰 UI 업로드 구현
- [x] 인포메이션뷰 - 맵뷰 중간 로딩뷰 2초 구현
- [x] TimelineView 데이터 불러오기 구현
- [x] RecordView 데이터 불러오기 구현
- [x] RecordView 지나간 포인트 ScrollView 구현
- [x] 기능확인, 데이터 저장, 읽기 확인
