### ISSUE TITLE
[FEAT] extension(color, font), component, viewBuilder 작업

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#5]
## 🛠 Issue

뷰 구성에 필요한 extention, viewBuilder를 만듭니다.

## 📝 To-do

- [x] color asset 적용
- [x] color extention 구현
- [x] font ~~~ 구현
- [x] buttonStyle 구현
- [x] Title ViewBulider 구현
- [x] subtitle ViewBulider 구현
