### ISSUE TITLE
[FEAT] 맵 뷰 데이터 연결, 마지막 뷰 데이터 연결

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#52]
## 🛠 Issue

연결되지 않은 맵뷰와 마지막 뷰 간의 연결을 구현합니다.
코어데이터 연결은 이 이슈를 마지막으로 작업이 종료됩니다.

## 📝 To-do

- [x] 맵 뷰 -> 레코드 뷰 넘어가기 전 CoreData에 WorkData 저장
- [x] 맵 뷰 안의 모달뷰 중 데이터 Display 안 된 곳 구현
- [x] 모든 뷰 간 연결 동작 완전 구현
- [x] 전체 플로우 애니메이션으로 찍기
