### ISSUE TITLE
[FIX] DataReceiveView, BackButton UI 수정 

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#60]
## 🛠 Issue

DataReceiveView의 TextField 관련 버그를 수정합니다.
또한 BackButton 기본 UI를 커스텀으로 변경합니다.

## 📝 To-do

- [x] TextField 입력 후 키보드가 내려가지 않는 버그 수정
- [x] 텍스트 미입력 또는 8자 이상 입력시 오류 문구 표시
- [x] BackButton 기본 UI 커스텀으로 변경("뒤로")
