### ISSUE TITLE
[FEAT] 지점 별 거리, 누적 산책 거리 CoreData 저장 기능 구현

### ISSUE THREAD

**Issue by DhKimy** [2023SST-InToTheSeoul/SanCheckHadge#63]
## 🛠 Issue

PointsModel 완성에 따른 지점 별 거리, 누적 산책 거리를 CoreData에 저장하는 기능을 구현합니다.

## 📝 To-do

- [x] 지점 별 거리 TrekkingModal에 표시
- [x] 누적 산책 거리 CoreData 저장
- [x] 누적 산책 거리에 따른 포인트 저장
- [x] RewardView 코인 변수 수정
- [x] Hedge 이미지 운동 데이터 개수별로 달라지는 것 구현
