### ISSUE TITLE
[FEAT] 맵뷰 기능 추가

### ISSUE THREAD

**Issue by seunggyun-jeong** [2023SST-InToTheSeoul/SanCheckHadge#71]
## 🛠 Issue
일부 기능 추가할 예정입니다.

## 📝 To-do
- [ ] Must waypoint 표시하기
- [x] 포인트 1부터 시작하도록
- [x] 두 번 이상 실행하면 시작지점과 1번 지점이 중복되어서 찍힘. 하지만 화면을 백그라운드로 나갔다가 들어오면 정상으로 됨.
