### ISSUE TITLE
[FEAT] 뷰 UI 수정

### ISSUE THREAD

**Issue by Taerogrammer** [2023SST-InToTheSeoul/SanCheckHadge#76]
## 📝 To-do

- [x] 온보딩 뷰 나이대 설정
- [x] 온보딩 뷰 gif 파일 재업로드. 화질 확인
- [x] 코인 획득 부분 기준값 확인
- [x] 코인 획득 부분 Text 넓이 확인
- [x] 권한 설정 부분 상세한 설명으로 변경
